### ISSUE TITLE
Error: *** Exception: 'Exception of type 'System.OutOfMemoryException' was thrown.'

### ISSUE THREAD

**Issue by hfleitas** [Microsoft/ml-server-text-classification#5]
```
Use NewsSQLPy
GO
	exec [dbo].[train_model] @model_key = 'LR';
```
Msg 39004, Level 16, State 20, Line 52
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 52
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData\MSSQLSERVER01\2F2E0B6D-096B-4A5D-AFB9-8D8346BCB091\sqlindb.py", line 201, in transform
    train_threads = 4)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\microsoftml\modules\logistic_regression.py", line 441, in rx_logistic_regression
    compute_context=compute_context)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\microsoftml\modules\ensemble.py", line 170, in fit
    return super().fit(**self.data_args)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\microsoftml\modules\base_learner.py", line 231, in fit
    telemetry_info=telemetry_info)

Msg 39019, Level 16, State 2, Line 52
An external script error occurred: 
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\microsoftml\utils\entrypoints.py", line 150, in run
    ret = tlc_bridge(maml_code=maml_code, analysis_type="RunGraph", **kargs)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\utils\RxFunctionUtils.py", line 8, in wrapper
    return func(*args,**kwds)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\microsoftml\utils\tlc_bridge.py", line 178, in tlc_bridge
    obj["params"] = call_parameters
TypeError: 'str' object does not support item assignment

SqlSatelliteCall error: Error in execution.  Check the output for more information.
STDOUT message(s) from external script: 
Rows Read: 20, Total Rows Processed: 20, Total Chunk Time: 0.033 seconds 
RxInSqlServer Compute Context:
------------------------------
connection_string: "Driver=SQL Server;Server=R90GTU6N;Database=NewsSQLPy;Trusted_Connection=true;"
num_tasks: 1
execution_timeout_seconds: 0
wait: True
console_output: False
auto_cleanup: True
packages_to_load: []
description: "sqlserver"
version: "1.0"
TlcBridge error: Error: *** Exception: 'Exception of type 'System.OutOfMemoryException' was thrown.'
Error in processing machine learning request.Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 643, in rx_sql_satellite_pool_call
    exec(inputfile.read())
  File "<string>", line 29, in <module>

STDOUT message(s) from external script: 
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 838, in rx_remote_call
    results = rx_resumeexecution(state_file = inputfile)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 125, in rx_resumeexecution
    return _state["function"](**_state["args"])
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 358, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.
====== R90GTU6N ( process 0 ) has started run at 2018-04-27 16:15:51 Eastern Daylight Time ======

Elapsed time to compute low/high values and/or factor levels: 1.076 secs.
 
Not adding a normalizer.
Beginning read for block: 1

STDOUT message(s) from external script: 
Rows Read: 11296, Read Time: 0.182, Transform Time: 0
Beginning read for block: 2
Beginning read for block: 1
Rows Read: 11296, Read Time: 0.14, Transform Time: 0
Beginning read for block: 2
Elapsed time: 00:00:23.2983978
Error: *** Exception: 'Exception of type 'System.OutOfMemoryException' was thrown.'
Error in processing machine learning request.
TlcBridge function failed. Please see the console output for more information.

SqlSatelliteCall function failed. Please see the console output for more information.
Traceback (most recent call last):
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 587, in rx_sql_satellite_call
    rx_native_call("SqlSatelliteCall", params)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 358, in rx_native_call

STDOUT message(s) from external script: 
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.

**Comment by hfleitas** [comment]
altered procedure [train_model] to turn-off multi-threading for [rx_logistic_regression](https://docs.microsoft.com/en-us/machine-learning-server/python-reference/microsoftml/rx-logistic-regression). 

Set train_threads = 1
Fixed issue.

````
# Train a logistic regression model. Set train_threads to 1 to turn off multi-threading due to out-of-memory errors.
logistic_model = rx_logistic_regression(formula = training_formula,
                                        data = News_Train_sql,
                                        method = "multiClass",
					l2_weight = 1, 
                                        l1_weight = 1,
                                        ml_transforms = text_transform_list,
                                        train_threads = 1)
````
