### ISSUE TITLE
Parameter name: value' ... text classification Newsgroups20

### ISSUE THREAD

**Issue by HectorMeneses333** [Microsoft/ml-server-text-classification#6]
Here's the output I'm getting:

RxInSqlServer Compute Context:
------------------------------
connection_string: "DRIVER=SQL Server;SERVER=localhost;DATABASE=TextClassification_Py;TRUSTED_CONNECTION=Yes"
num_tasks: 1
execution_timeout_seconds: 0
wait: True
console_output: False
auto_cleanup: True
packages_to_load: []
description: "sqlserver"
version: "1.0"

TlcBridge error: Error: *** Exception: 'Value cannot be null.

Parameter name: value'
Error in processing machine learning request.Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 462, in rx_sql_satellite_pool_call
    exec(inputfile.read())
  File "<string>", line 29, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 871, in rx_remote_call
    results = rx_resumeexecution(state_file = inputfile)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 552, in rx_resumeexecution
    return _state["function"](**_state["args"])
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib...

Backend Qt5Agg is interactive backend. Turning interactive mode on.
TypeError("'str' object does not support item assignment",)
Stack trace:
 >  File "c:\users\hmeneses\documents\ml-server-text-classification\python\textclassification.py", line 126, in <module>
 >    train_threads = 1

When I debugged this in Visual Studio I got the following as well:

RxInSqlServer Compute Context:
------------------------------
connection_string: "DRIVER=SQL Server;SERVER=localhost;DATABASE=TextClassification_Py;TRUSTED_CONNECTION=Yes"
num_tasks: 1
execution_timeout_seconds: 0
wait: True
console_output: False
auto_cleanup: True
packages_to_load: []
description: "sqlserver"
version: "1.0"

TlcBridge error: The file or directory 'work\sample-ds1.xdf' cannot be found.Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 462, in rx_sql_satellite_pool_call
    exec(inputfile.read())
  File "<string>", line 29, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 871, in rx_remote_call
    results = rx_resumeexecution(state_file = inputfile)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 552, in rx_resumeexecution
    return _state["function"](**_state["args"])
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 29...

Unable to retrieve sqlServerArgs
TlcBridge error: Unable to retrieve sqlServerArgs
TlcBridge function failed. Please see the console output for more information.

**Comment by jeroenterheerdt** [comment]
@HectorMeneses333 I do not see the `textclassification.py` script anywhere. Which script are you using?

**Comment by renaudmontes1** [comment]
Type 'text' for SolutionName when you are running the scripts, has been confusing all this along, like this:
Supply values for the following parameters:
ServerName: localhost
SolutionName: text
InstallPy: yes
InstallR: yes

This will create two dbs: text_R and text_Py

Hope this helps
